// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/prep-qc/PrepQC.tsx": () => import("../components/mockups/prep-qc/PrepQC.tsx")
};
